import destinations from "@/data/destinations.json";
import type { DestinationOption } from "@/components/forms/DestinationSearch";

// Only include items that already have a slug (generated by your scripts)
export const destinationOptions: DestinationOption[] = (destinations as any[])
  .filter((d) => typeof d.slug === "string" && d.slug.length > 0)
  .map((d) => ({
    name: d.name,
    slug: d.slug, // ✅ use the generated slug only
    country: d.country,
    code: d.code,
    region: d.region,
  }));